<?php
/**
 * SimpleAuthorizationCreate
 *
 * PHP version 5
 *
 * @category Class
 * @package  Coucounco\Airkey\Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVVA AirKey Cloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v18.0.4
 * Contact: office-wien@evva.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.41
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Coucounco\Airkey\Swagger\Client\Model;

use \ArrayAccess;
use \Coucounco\Airkey\Swagger\Client\ObjectSerializer;

/**
 * SimpleAuthorizationCreate Class Doc Comment
 *
 * @category Class
 * @description Model that describes a simple authorization of a medium to be created in the access control system.
 * @package  Coucounco\Airkey\Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SimpleAuthorizationCreate implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'SimpleAuthorizationCreate';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'authorization_info' => '\Coucounco\Airkey\Swagger\Client\Model\SimpleAuthorizationInfo',
        'medium_id' => 'int',
        'lock_id' => 'int',
        'area_id' => 'int',
        'remove_all_existing_authorizations_for_pair' => 'bool',
        'push_message' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'authorization_info' => null,
        'medium_id' => 'int64',
        'lock_id' => 'int64',
        'area_id' => 'int64',
        'remove_all_existing_authorizations_for_pair' => null,
        'push_message' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'authorization_info' => 'authorizationInfo',
        'medium_id' => 'mediumId',
        'lock_id' => 'lockId',
        'area_id' => 'areaId',
        'remove_all_existing_authorizations_for_pair' => 'removeAllExistingAuthorizationsForPair',
        'push_message' => 'pushMessage'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'authorization_info' => 'setAuthorizationInfo',
        'medium_id' => 'setMediumId',
        'lock_id' => 'setLockId',
        'area_id' => 'setAreaId',
        'remove_all_existing_authorizations_for_pair' => 'setRemoveAllExistingAuthorizationsForPair',
        'push_message' => 'setPushMessage'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'authorization_info' => 'getAuthorizationInfo',
        'medium_id' => 'getMediumId',
        'lock_id' => 'getLockId',
        'area_id' => 'getAreaId',
        'remove_all_existing_authorizations_for_pair' => 'getRemoveAllExistingAuthorizationsForPair',
        'push_message' => 'getPushMessage'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['authorization_info'] = isset($data['authorization_info']) ? $data['authorization_info'] : null;
        $this->container['medium_id'] = isset($data['medium_id']) ? $data['medium_id'] : null;
        $this->container['lock_id'] = isset($data['lock_id']) ? $data['lock_id'] : null;
        $this->container['area_id'] = isset($data['area_id']) ? $data['area_id'] : null;
        $this->container['remove_all_existing_authorizations_for_pair'] = isset($data['remove_all_existing_authorizations_for_pair']) ? $data['remove_all_existing_authorizations_for_pair'] : null;
        $this->container['push_message'] = isset($data['push_message']) ? $data['push_message'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['authorization_info'] === null) {
            $invalidProperties[] = "'authorization_info' can't be null";
        }
        if ($this->container['medium_id'] === null) {
            $invalidProperties[] = "'medium_id' can't be null";
        }
        if (!is_null($this->container['push_message']) && (mb_strlen($this->container['push_message']) > 160)) {
            $invalidProperties[] = "invalid value for 'push_message', the character length must be smaller than or equal to 160.";
        }

        if (!is_null($this->container['push_message']) && (mb_strlen($this->container['push_message']) < 0)) {
            $invalidProperties[] = "invalid value for 'push_message', the character length must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets authorization_info
     *
     * @return \Coucounco\Airkey\Swagger\Client\Model\SimpleAuthorizationInfo
     */
    public function getAuthorizationInfo()
    {
        return $this->container['authorization_info'];
    }

    /**
     * Sets authorization_info
     *
     * @param \Coucounco\Airkey\Swagger\Client\Model\SimpleAuthorizationInfo $authorization_info Details of a simple authorization
     *
     * @return $this
     */
    public function setAuthorizationInfo($authorization_info)
    {
        $this->container['authorization_info'] = $authorization_info;

        return $this;
    }

    /**
     * Gets medium_id
     *
     * @return int
     */
    public function getMediumId()
    {
        return $this->container['medium_id'];
    }

    /**
     * Sets medium_id
     *
     * @param int $medium_id Medium to which this authorization should be defined
     *
     * @return $this
     */
    public function setMediumId($medium_id)
    {
        $this->container['medium_id'] = $medium_id;

        return $this;
    }

    /**
     * Gets lock_id
     *
     * @return int
     */
    public function getLockId()
    {
        return $this->container['lock_id'];
    }

    /**
     * Sets lock_id
     *
     * @param int $lock_id Lock for which the medium should be authorized. Required when no area id is set.
     *
     * @return $this
     */
    public function setLockId($lock_id)
    {
        $this->container['lock_id'] = $lock_id;

        return $this;
    }

    /**
     * Gets area_id
     *
     * @return int
     */
    public function getAreaId()
    {
        return $this->container['area_id'];
    }

    /**
     * Sets area_id
     *
     * @param int $area_id Area for which the medium should be authorized. Required when no lock id is set.
     *
     * @return $this
     */
    public function setAreaId($area_id)
    {
        $this->container['area_id'] = $area_id;

        return $this;
    }

    /**
     * Gets remove_all_existing_authorizations_for_pair
     *
     * @return bool
     */
    public function getRemoveAllExistingAuthorizationsForPair()
    {
        return $this->container['remove_all_existing_authorizations_for_pair'];
    }

    /**
     * Sets remove_all_existing_authorizations_for_pair
     *
     * @param bool $remove_all_existing_authorizations_for_pair Removes all authorizations for the given medium – lock or medium – area pair before creating the given simple authorization (avoids conflict potential which may result in failure).
     *
     * @return $this
     */
    public function setRemoveAllExistingAuthorizationsForPair($remove_all_existing_authorizations_for_pair)
    {
        $this->container['remove_all_existing_authorizations_for_pair'] = $remove_all_existing_authorizations_for_pair;

        return $this;
    }

    /**
     * Gets push_message
     *
     * @return string
     */
    public function getPushMessage()
    {
        return $this->container['push_message'];
    }

    /**
     * Sets push_message
     *
     * @param string $push_message Notification text that will be shown on the phone for new/changed authorizations. Default text will be used if not set.
     *
     * @return $this
     */
    public function setPushMessage($push_message)
    {
        if (!is_null($push_message) && (mb_strlen($push_message) > 160)) {
            throw new \InvalidArgumentException('invalid length for $push_message when calling SimpleAuthorizationCreate., must be smaller than or equal to 160.');
        }
        if (!is_null($push_message) && (mb_strlen($push_message) < 0)) {
            throw new \InvalidArgumentException('invalid length for $push_message when calling SimpleAuthorizationCreate., must be bigger than or equal to 0.');
        }

        $this->container['push_message'] = $push_message;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


