<?php
/**
 * MaintenanceTasksApi
 * PHP version 5
 *
 * @category Class
 * @package  Coucounco\Airkey\Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVVA AirKey Cloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v14.40.2
 * Contact: office-wien@evva.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Coucounco\Airkey\Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Coucounco\Airkey\Swagger\Client\ApiException;
use Coucounco\Airkey\Swagger\Client\Configuration;
use Coucounco\Airkey\Swagger\Client\HeaderSelector;
use Coucounco\Airkey\Swagger\Client\ObjectSerializer;

/**
 * MaintenanceTasksApi Class Doc Comment
 *
 * @category Class
 * @package  Coucounco\Airkey\Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MaintenanceTasksApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getMaintenanceTasks
     *
     * Gets all maintenance tasks.
     *
     * @param  int $lock_id Filter maintenance tasks by lock id (optional)
     * @param  string $lock_identifier Filter maintenance tasks by lock identifier (optional)
     * @param  string $door_name Filter maintenance tasks by door name (optional)
     * @param  int $offset Offset for paging (optional)
     * @param  int $limit Limit of result size (optional)
     *
     * @throws \Coucounco\Airkey\Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Coucounco\Airkey\Swagger\Client\Model\MaintenanceTaskPagingList
     */
    public function getMaintenanceTasks($lock_id = null, $lock_identifier = null, $door_name = null, $offset = null, $limit = null)
    {
        list($response) = $this->getMaintenanceTasksWithHttpInfo($lock_id, $lock_identifier, $door_name, $offset, $limit);
        return $response;
    }

    /**
     * Operation getMaintenanceTasksWithHttpInfo
     *
     * Gets all maintenance tasks.
     *
     * @param  int $lock_id Filter maintenance tasks by lock id (optional)
     * @param  string $lock_identifier Filter maintenance tasks by lock identifier (optional)
     * @param  string $door_name Filter maintenance tasks by door name (optional)
     * @param  int $offset Offset for paging (optional)
     * @param  int $limit Limit of result size (optional)
     *
     * @throws \Coucounco\Airkey\Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Coucounco\Airkey\Swagger\Client\Model\MaintenanceTaskPagingList, HTTP status code, HTTP response headers (array of strings)
     */
    public function getMaintenanceTasksWithHttpInfo($lock_id = null, $lock_identifier = null, $door_name = null, $offset = null, $limit = null)
    {
        $returnType = '\Coucounco\Airkey\Swagger\Client\Model\MaintenanceTaskPagingList';
        $request = $this->getMaintenanceTasksRequest($lock_id, $lock_identifier, $door_name, $offset, $limit);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Coucounco\Airkey\Swagger\Client\Model\MaintenanceTaskPagingList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getMaintenanceTasksAsync
     *
     * Gets all maintenance tasks.
     *
     * @param  int $lock_id Filter maintenance tasks by lock id (optional)
     * @param  string $lock_identifier Filter maintenance tasks by lock identifier (optional)
     * @param  string $door_name Filter maintenance tasks by door name (optional)
     * @param  int $offset Offset for paging (optional)
     * @param  int $limit Limit of result size (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMaintenanceTasksAsync($lock_id = null, $lock_identifier = null, $door_name = null, $offset = null, $limit = null)
    {
        return $this->getMaintenanceTasksAsyncWithHttpInfo($lock_id, $lock_identifier, $door_name, $offset, $limit)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getMaintenanceTasksAsyncWithHttpInfo
     *
     * Gets all maintenance tasks.
     *
     * @param  int $lock_id Filter maintenance tasks by lock id (optional)
     * @param  string $lock_identifier Filter maintenance tasks by lock identifier (optional)
     * @param  string $door_name Filter maintenance tasks by door name (optional)
     * @param  int $offset Offset for paging (optional)
     * @param  int $limit Limit of result size (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMaintenanceTasksAsyncWithHttpInfo($lock_id = null, $lock_identifier = null, $door_name = null, $offset = null, $limit = null)
    {
        $returnType = '\Coucounco\Airkey\Swagger\Client\Model\MaintenanceTaskPagingList';
        $request = $this->getMaintenanceTasksRequest($lock_id, $lock_identifier, $door_name, $offset, $limit);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getMaintenanceTasks'
     *
     * @param  int $lock_id Filter maintenance tasks by lock id (optional)
     * @param  string $lock_identifier Filter maintenance tasks by lock identifier (optional)
     * @param  string $door_name Filter maintenance tasks by door name (optional)
     * @param  int $offset Offset for paging (optional)
     * @param  int $limit Limit of result size (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getMaintenanceTasksRequest($lock_id = null, $lock_identifier = null, $door_name = null, $offset = null, $limit = null)
    {
        if ($offset !== null && $offset < 0) {
            throw new \InvalidArgumentException('invalid value for "$offset" when calling MaintenanceTasksApi.getMaintenanceTasks, must be bigger than or equal to 0.');
        }

        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling MaintenanceTasksApi.getMaintenanceTasks, must be bigger than or equal to 1.');
        }


        $resourcePath = '/v1/maintenance-tasks';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($lock_id !== null) {
            $queryParams['lockId'] = ObjectSerializer::toQueryValue($lock_id);
        }
        // query params
        if ($lock_identifier !== null) {
            $queryParams['lockIdentifier'] = ObjectSerializer::toQueryValue($lock_identifier);
        }
        // query params
        if ($door_name !== null) {
            $queryParams['doorName'] = ObjectSerializer::toQueryValue($door_name);
        }
        // query params
        if ($offset !== null) {
            $queryParams['offset'] = ObjectSerializer::toQueryValue($offset);
        }
        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-API-Key');
        if ($apiKey !== null) {
            $headers['X-API-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
