<?php
/**
 * AuthorizationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVVA AirKey Cloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v14.40.2
 * Contact: office-wien@evva.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AuthorizationTest Class Doc Comment
 *
 * @category    Class
 * @description Model that describes an authorization defined in the access control system (NOTE: Either the lock or the area is set, not both).
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AuthorizationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Authorization"
     */
    public function testAuthorization()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "medium"
     */
    public function testPropertyMedium()
    {
    }

    /**
     * Test attribute "lock"
     */
    public function testPropertyLock()
    {
    }

    /**
     * Test attribute "area"
     */
    public function testPropertyArea()
    {
    }

    /**
     * Test attribute "person_id"
     */
    public function testPropertyPersonId()
    {
    }

    /**
     * Test attribute "current_state"
     */
    public function testPropertyCurrentState()
    {
    }

    /**
     * Test attribute "created_on"
     */
    public function testPropertyCreatedOn()
    {
    }

    /**
     * Test attribute "updated_on"
     */
    public function testPropertyUpdatedOn()
    {
    }

    /**
     * Test attribute "synchronized_on"
     */
    public function testPropertySynchronizedOn()
    {
    }

    /**
     * Test attribute "deletion_requested"
     */
    public function testPropertyDeletionRequested()
    {
    }

    /**
     * Test attribute "authorization_info_list"
     */
    public function testPropertyAuthorizationInfoList()
    {
    }

    /**
     * Test attribute "custom"
     */
    public function testPropertyCustom()
    {
    }
}
