<?php
/**
 * AuthorizationInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Coucounco\Airkey\Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVVA AirKey Cloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v14.40.2
 * Contact: office-wien@evva.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Coucounco\Airkey\Swagger\Client;

/**
 * AuthorizationInfoTest Class Doc Comment
 *
 * @category    Class
 * @description Model that describes details of an authorization. Possible types of authorizations are: &lt;br/&gt;&lt;a href&#x3D;\&quot;#model-PermanentAuthorizationInfo\&quot;&gt;PermanentAuthorizationInfo&lt;/a&gt;: describes a permanent authorization with or without an expiration date (\&quot;validFromDate\&quot;, \&quot;validToDate\&quot;) &lt;br/&gt;&lt;a href&#x3D;\&quot;#model-PeriodicalAuthorizationInfo\&quot;&gt;PeriodicalAuthorizationInfo&lt;/a&gt;: describes an authorization with periodic access with or without an expiration date (\&quot;periodicalPeriods\&quot;, \&quot;validFromDate\&quot;, \&quot;validToDate\&quot;) &lt;br/&gt;&lt;a href&#x3D;\&quot;#model-OneDayAuthorizationInfo\&quot;&gt;OneDayAuthorizationInfo&lt;/a&gt;: describes a temporary authorization for a day or a period of the day (\&quot;validAtDate\&quot;, \&quot;startTime\&quot;, \&quot;endTime\&quot;) &lt;br/&gt;&lt;a href&#x3D;\&quot;#model-SimpleAuthorizationInfo\&quot;&gt;SimpleAuthorizationInfo&lt;/a&gt;: describes an authorization for basic needs, e.g., multi-day-capability, from-to with minute granularity, no gaps, no holiday calendar (\&quot;validFrom\&quot;, \&quot;validTo\&quot;)
 * @package     Coucounco\Airkey\Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AuthorizationInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AuthorizationInfo"
     */
    public function testAuthorizationInfo()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }
}
