<?php
/**
 * AuthorizationCreateTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Coucounco\Airkey\Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVVA AirKey Cloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v18.0.4
 * Contact: office-wien@evva.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.41
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Coucounco\Airkey\Swagger\Client;

/**
 * AuthorizationCreateTest Class Doc Comment
 *
 * @category    Class
 * @description Model that describes an authorization of a medium to be created in the access control system (NOTE: Either the lockId or the areaId must be set, not both).
 * @package     Coucounco\Airkey\Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AuthorizationCreateTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AuthorizationCreate"
     */
    public function testAuthorizationCreate()
    {
    }

    /**
     * Test attribute "medium_id"
     */
    public function testPropertyMediumId()
    {
    }

    /**
     * Test attribute "area_id"
     */
    public function testPropertyAreaId()
    {
    }

    /**
     * Test attribute "lock_id"
     */
    public function testPropertyLockId()
    {
    }

    /**
     * Test attribute "authorization_info_list"
     */
    public function testPropertyAuthorizationInfoList()
    {
    }
}
