<?php
/**
 * FixedMediumSimpleAuthorizationCreateTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Coucounco\Airkey\Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVVA AirKey Cloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v14.40.2
 * Contact: office-wien@evva.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Coucounco\Airkey\Swagger\Client;

/**
 * FixedMediumSimpleAuthorizationCreateTest Class Doc Comment
 *
 * @category    Class
 * @description Model that is same as SimpleAuthorizationCreate, only with a fixed medium id (can’t be manually set, context dependant retrieval).
 * @package     Coucounco\Airkey\Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FixedMediumSimpleAuthorizationCreateTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FixedMediumSimpleAuthorizationCreate"
     */
    public function testFixedMediumSimpleAuthorizationCreate()
    {
    }

    /**
     * Test attribute "authorization_info"
     */
    public function testPropertyAuthorizationInfo()
    {
    }

    /**
     * Test attribute "lock_id"
     */
    public function testPropertyLockId()
    {
    }

    /**
     * Test attribute "area_id"
     */
    public function testPropertyAreaId()
    {
    }

    /**
     * Test attribute "remove_all_existing_authorizations_for_pair"
     */
    public function testPropertyRemoveAllExistingAuthorizationsForPair()
    {
    }
}
