<?php
/**
 * LockProtocolEntryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Coucounco\Airkey\Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVVA AirKey Cloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v14.40.2
 * Contact: office-wien@evva.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Coucounco\Airkey\Swagger\Client;

/**
 * LockProtocolEntryTest Class Doc Comment
 *
 * @category    Class
 * @description Model that describes a protocol entry associated with a lock defined in the access control system.
 * @package     Coucounco\Airkey\Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LockProtocolEntryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LockProtocolEntry"
     */
    public function testLockProtocolEntry()
    {
    }

    /**
     * Test attribute "event_category"
     */
    public function testPropertyEventCategory()
    {
    }

    /**
     * Test attribute "event"
     */
    public function testPropertyEvent()
    {
    }

    /**
     * Test attribute "details"
     */
    public function testPropertyDetails()
    {
    }

    /**
     * Test attribute "lock_utc_delta"
     */
    public function testPropertyLockUtcDelta()
    {
    }

    /**
     * Test attribute "medium"
     */
    public function testPropertyMedium()
    {
    }

    /**
     * Test attribute "operator_name"
     */
    public function testPropertyOperatorName()
    {
    }

    /**
     * Test attribute "source_lock"
     */
    public function testPropertySourceLock()
    {
    }

    /**
     * Test attribute "source_medium"
     */
    public function testPropertySourceMedium()
    {
    }

    /**
     * Test attribute "timestamp"
     */
    public function testPropertyTimestamp()
    {
    }
}
